#!/bin/bash
# Co powinno być w takim skrypcie?
#  - Możliwość wyboru screenshota całego ekranu, okna
#  - Opóźnienie
#  - Zapisanie do katalogu
#  - Kopiowanie do schowka (xclip)

DEPENDENCIES=( "scrot" "xclip" )
PICTURES="$HOME/Obrazy/Screenshoty"

function check_dependencies() {
  declare -a dependencies=(${!@})

  for item in ${dependencies[@]}; do
    if [ ! $(which ${item}) ]; then
      echo "Brakuje pakietu $item!"
      return 1
    fi
  done
}

function check_directory() {
  declare -a dir=${!1}

  if [ -d $dir ]; then
    echo 1
  else
    mkdir -p $dir
    if [ $? -ne 0 ]; then
      echo "Nie można stworzyć katalogu $dir! Wychodzę!"
      return 1
    fi
    echo 1
  fi
}

function take_screenshot() {
  if [ $(check_directory PICTURES) -eq "1" && $(check_dependencies DEPENDENCIES[@] -eq "1" )]; then
    scrot 'screenshot_%d-%m-%Y_$H-%M-%S.png'
  fi
}

take_screenshot

